import {
  Boxes,
  Briefcase,
  Clapperboard,
  ShoppingCart,
  Mail,
  Scissors,
  MonitorPlay,
  Search,
  Database,
  Workflow,
  Repeat,
  Radar,
  HelpCircle,
  Hammer,
  Layout,
  Rocket,
  Users,
  Wrench,
  CreditCard,
  Megaphone,
  TrendingUp,
  Target,
  Filter,
  Sparkles,
  Phone,
  FileText,
  Clock,
  RefreshCw,
  Award,
  Eye,
  Wand2,
  Layers,
  Flame,
  Send,
  PenTool,
  Globe,
  Heart,
  ThumbsUp,
  Coins,
  Shield,
  List,
  Download,
  BarChart,
  Package,
  Store,
  Truck,
  Bot,
  Gem,
  Link,
  Mic,
  Image,
  Film,
  Upload,
  Video,
  CheckCircle,
  BadgeDollarSign,
  PhoneCall,
  CalendarCheck,
  MessageCircle,
  Star,
  type LucideIcon,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  boxes: Boxes,
  briefcase: Briefcase,
  clapperboard: Clapperboard,
  'shopping-cart': ShoppingCart,
  mail: Mail,
  scissors: Scissors,
  youtube: MonitorPlay,
  search: Search,
  database: Database,
  workflow: Workflow,
  repeat: Repeat,
  radar: Radar,
  'help-circle': HelpCircle,
  hammer: Hammer,
  layout: Layout,
  rocket: Rocket,
  users: Users,
  wrench: Wrench,
  'credit-card': CreditCard,
  megaphone: Megaphone,
  'trending-up': TrendingUp,
  target: Target,
  filter: Filter,
  sparkles: Sparkles,
  phone: Phone,
  'file-text': FileText,
  clock: Clock,
  'refresh-cw': RefreshCw,
  award: Award,
  eye: Eye,
  wand: Wand2,
  layers: Layers,
  flame: Flame,
  send: Send,
  'pen-tool': PenTool,
  globe: Globe,
  heart: Heart,
  'thumbs-up': ThumbsUp,
  coins: Coins,
  shield: Shield,
  list: List,
  download: Download,
  'bar-chart': BarChart,
  package: Package,
  store: Store,
  truck: Truck,
  bot: Bot,
  gem: Gem,
  link: Link,
  mic: Mic,
  image: Image,
  film: Film,
  upload: Upload,
  video: Video,
  'check-circle': CheckCircle,
  'badge-dollar-sign': BadgeDollarSign,
  'phone-call': PhoneCall,
  'calendar-check': CalendarCheck,
  'message-circle': MessageCircle,
  star: Star,
}

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? HelpCircle
}
